/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { customFetch } from './fetcher';
export type UpdateNodeCommandAttributes = {[key: string]: { [key: string]: unknown }};

export interface UpdateNodeCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  label?: string;
  description?: string;
  attributes?: UpdateNodeCommandAttributes;
  positionX?: number;
  positionY?: number;
}

export type CvNodeDtoType = typeof CvNodeDtoType[keyof typeof CvNodeDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CvNodeDtoType = {
  PROFILE: 'PROFILE',
  CATEGORY: 'CATEGORY',
  ITEM: 'ITEM',
  SKILL_GROUP: 'SKILL_GROUP',
  SKILL: 'SKILL',
} as const;

export type CvNodeDtoAttributes = {[key: string]: { [key: string]: unknown }};

export interface CvNodeDto {
  id?: string;
  type?: CvNodeDtoType;
  parentId?: string;
  label?: string;
  description?: string;
  attributes?: CvNodeDtoAttributes;
  positionX?: number;
  positionY?: number;
}

export interface CreateSkillCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  /** @minLength 1 */
  label?: string;
  description?: string;
  positionX?: number;
  positionY?: number;
  proficiencyLevel?: string;
  yearsOfExperience?: number;
}

export interface CreateSkillGroupCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  /** @minLength 1 */
  label?: string;
  description?: string;
  positionX?: number;
  positionY?: number;
  proficiencyLevel?: string;
}

export interface CreateProfileCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  /** @minLength 1 */
  label?: string;
  description?: string;
  positionX?: number;
  positionY?: number;
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  title?: string;
  subtitle?: string;
  experience?: string;
  email?: string;
  location?: string;
  photoUrl?: string;
}

export interface CreateItemCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  /** @minLength 1 */
  label?: string;
  description?: string;
  positionX?: number;
  positionY?: number;
  company?: string;
  dateRange?: string;
  location?: string;
  highlights?: string[];
  technologies?: string[];
}

export interface CreateCategoryCommand {
  /** @minLength 1 */
  id?: string;
  parentId?: string;
  /** @minLength 1 */
  label?: string;
  description?: string;
  positionX?: number;
  positionY?: number;
  /** @minLength 1 */
  sectionId?: string;
}

export interface CvDataDto {
  nodes?: CvNodeDto[];
}

export type Health200 = {[key: string]: { [key: string]: unknown }};

export type SearchParams = {
q: string;
};

export type getNodeResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type getNodeResponseSuccess = (getNodeResponse200) & {
  headers: Headers;
};
;

export type getNodeResponse = (getNodeResponseSuccess)

export const getGetNodeUrl = (id: string,) => {


  

  return `/api/cv/nodes/${id}`
}

export const getNode = async (id: string, options?: RequestInit): Promise<getNodeResponse> => {
  
  return customFetch<getNodeResponse>(getGetNodeUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type updateNodeResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type updateNodeResponseSuccess = (updateNodeResponse200) & {
  headers: Headers;
};
;

export type updateNodeResponse = (updateNodeResponseSuccess)

export const getUpdateNodeUrl = (id: string,) => {


  

  return `/api/cv/nodes/${id}`
}

export const updateNode = async (id: string,
    updateNodeCommand: UpdateNodeCommand, options?: RequestInit): Promise<updateNodeResponse> => {
  
  return customFetch<updateNodeResponse>(getUpdateNodeUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateNodeCommand,)
  }
);}



export type deleteNodeResponse200 = {
  data: void
  status: 200
}
    
export type deleteNodeResponseSuccess = (deleteNodeResponse200) & {
  headers: Headers;
};
;

export type deleteNodeResponse = (deleteNodeResponseSuccess)

export const getDeleteNodeUrl = (id: string,) => {


  

  return `/api/cv/nodes/${id}`
}

export const deleteNode = async (id: string, options?: RequestInit): Promise<deleteNodeResponse> => {
  
  return customFetch<deleteNodeResponse>(getDeleteNodeUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



export type createSkillResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type createSkillResponseSuccess = (createSkillResponse200) & {
  headers: Headers;
};
;

export type createSkillResponse = (createSkillResponseSuccess)

export const getCreateSkillUrl = () => {


  

  return `/api/cv/nodes/skill`
}

export const createSkill = async (createSkillCommand: CreateSkillCommand, options?: RequestInit): Promise<createSkillResponse> => {
  
  return customFetch<createSkillResponse>(getCreateSkillUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSkillCommand,)
  }
);}



export type createSkillGroupResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type createSkillGroupResponseSuccess = (createSkillGroupResponse200) & {
  headers: Headers;
};
;

export type createSkillGroupResponse = (createSkillGroupResponseSuccess)

export const getCreateSkillGroupUrl = () => {


  

  return `/api/cv/nodes/skill-group`
}

export const createSkillGroup = async (createSkillGroupCommand: CreateSkillGroupCommand, options?: RequestInit): Promise<createSkillGroupResponse> => {
  
  return customFetch<createSkillGroupResponse>(getCreateSkillGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSkillGroupCommand,)
  }
);}



export type createProfileResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type createProfileResponseSuccess = (createProfileResponse200) & {
  headers: Headers;
};
;

export type createProfileResponse = (createProfileResponseSuccess)

export const getCreateProfileUrl = () => {


  

  return `/api/cv/nodes/profile`
}

export const createProfile = async (createProfileCommand: CreateProfileCommand, options?: RequestInit): Promise<createProfileResponse> => {
  
  return customFetch<createProfileResponse>(getCreateProfileUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProfileCommand,)
  }
);}



export type createItemResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type createItemResponseSuccess = (createItemResponse200) & {
  headers: Headers;
};
;

export type createItemResponse = (createItemResponseSuccess)

export const getCreateItemUrl = () => {


  

  return `/api/cv/nodes/item`
}

export const createItem = async (createItemCommand: CreateItemCommand, options?: RequestInit): Promise<createItemResponse> => {
  
  return customFetch<createItemResponse>(getCreateItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createItemCommand,)
  }
);}



export type createCategoryResponse200 = {
  data: CvNodeDto
  status: 200
}
    
export type createCategoryResponseSuccess = (createCategoryResponse200) & {
  headers: Headers;
};
;

export type createCategoryResponse = (createCategoryResponseSuccess)

export const getCreateCategoryUrl = () => {


  

  return `/api/cv/nodes/category`
}

export const createCategory = async (createCategoryCommand: CreateCategoryCommand, options?: RequestInit): Promise<createCategoryResponse> => {
  
  return customFetch<createCategoryResponse>(getCreateCategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCategoryCommand,)
  }
);}



export type healthResponse200 = {
  data: Health200
  status: 200
}
    
export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
;

export type healthResponse = (healthResponseSuccess)

export const getHealthUrl = () => {


  

  return `/api/health`
}

export const health = async ( options?: RequestInit): Promise<healthResponse> => {
  
  return customFetch<healthResponse>(getHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getAllNodesResponse200 = {
  data: CvDataDto
  status: 200
}
    
export type getAllNodesResponseSuccess = (getAllNodesResponse200) & {
  headers: Headers;
};
;

export type getAllNodesResponse = (getAllNodesResponseSuccess)

export const getGetAllNodesUrl = () => {


  

  return `/api/cv`
}

export const getAllNodes = async ( options?: RequestInit): Promise<getAllNodesResponse> => {
  
  return customFetch<getAllNodesResponse>(getGetAllNodesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type searchResponse200 = {
  data: CvNodeDto[]
  status: 200
}
    
export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/cv/search?${stringifiedParams}` : `/api/cv/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {
  
  return customFetch<searchResponse>(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getChildrenResponse200 = {
  data: CvNodeDto[]
  status: 200
}
    
export type getChildrenResponseSuccess = (getChildrenResponse200) & {
  headers: Headers;
};
;

export type getChildrenResponse = (getChildrenResponseSuccess)

export const getGetChildrenUrl = (id: string,) => {


  

  return `/api/cv/nodes/${id}/children`
}

export const getChildren = async (id: string, options?: RequestInit): Promise<getChildrenResponse> => {
  
  return customFetch<getChildrenResponse>(getGetChildrenUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
